# Generated by Django 3.2.3 on 2025-05-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='updated',
        ),
    ]
