# Generated by Django 3.2.3 on 2025-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_favorite_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='created',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата добавления в избранное'),
        ),
    ]
