# Generated by Django 3.2.3 on 2025-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250509_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в корзину'),
        ),
    ]
