# Generated by Django 3.2.3 on 2025-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default.jpg', null=True, upload_to='media/avatars/', verbose_name='Аватар'),
        ),
    ]
