# Generated by Django 3.2.3 on 2025-05-09 07:32

import pathlib

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250508_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Dev/sp18/foodgram/backend/foodgram/media/users/avatar'), verbose_name='Аватар'),
        ),
    ]
