# Generated by Django 3.2.3 on 2025-05-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_favorite_updated'),
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', through='recipes.Favorite', to='recipes.Recipe', verbose_name='Избранные рецепты'),
        ),
    ]
