# Generated by Django 3.2.3 on 2025-05-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_shoppingcart_created'),
        ('users', '0007_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='shopping_cart', through='recipes.ShoppingCart', to='recipes.Recipe', verbose_name='Список покупок'),
        ),
    ]
